- README.md
- ngx_http_vod_request_parse.c
- vod/dash/dash_packager.c
- vod/media_format.h
- vod/media_set_parser.c
Support DASH role schemes as defined in ISO/IEC 23009-1 Section 5.8.5.5 per sequence.
```json
{
"sequences": [
{
"clips": [
{
"type": "source",
"path": "tears-of-steel-avc1-1500k.mp4"
}
],
"roles": ["main"]  
},
{
"clips": [
{
"type": "source",
"path": "tears-of-steel-aac-128k.mp4"
}
],
"language": "eng",
"label": "English",
"roles": ["main"]
},
{
"clips": [
{
"type": "source",
"path": "tears-of-steel-en.srt"
}
],
"language": "eng",
"label": "English",
"roles": ["subtitle"]
},
{
"clips": [
{
"type": "source",
"path": "tears-of-steel-en-hoh.srt"
}
],
"language": "eng",
"label": "English (CC)",
"roles": ["subtitle", "caption"]
}
]
}
```
- For roles such as `caption` or `description`, the label must be explicitly specified. The default label does not take roles into account.
- In adaptation …
> Add DASH role scheme support

- README.md
- ngx_http_vod_request_parse.c
- vod/hls/m3u8_builder.c
- vod/media_format.h
- vod/media_set_parser.c
Support HLS characteristics as defined in [RFC 8216 Section 4.3.4.1](https://datatracker.ietf.org/doc/html/rfc8216#section-4.3.4.1) per sequence. Additionally, support FORCED subtitles and make AUTOSELECT adjustable.
```json
{
"sequences": [
{
"clips": [
{
"type": "source",
"path": "tears-of-steel-avc1-1500k.mp4"
}
]
},
{
"clips": [
{
"type": "source",
"path": "tears-of-steel-aac-128k.mp4"
}
],
"language": "eng"
},
{
"clips": [
{
"type": "source",
"path": "tears-of-steel-en-hoh.srt"
}
],
"language": "eng",
"label": "English (CC)",
"characteristics": "public.accessibility.transcribes-spoken-dialog"
},
{
"clips": [
{
"type": "source",
"path": "tears-of-steel-en-for.srt"
}
],
"language": "eng",
"label":"English (forced)",
"forced": true
}
]
}
```
- For characteristics such as …
> Add HLS characteristics support

- vod/hls/m3u8_builder.c
As per [documentation](https://github.com/diogoazevedos/nginx-vod-module/blob/0ddb399c1c75cd8e94481cb90631f12a7d0e8739/README.md#sequence):
> `default` - If not specified, the first EXT-X-MEDIA tag in **each group** returns DEFAULT=YES.
The first EXT-X-MEDIA tag in **each type** returns DEFAULT=YES.
The first EXT-X-MEDIA tag in **each group** returns DEFAULT=YES.
> Ensure that each audio group has a default

- vod/hls/m3u8_builder.c
Change the behavior of taking the first audio track in a multi-bitrate scenario to choosing the last one, assuming it has a higher bitrate.
> Use last audio track assuming higher bitrate

- README.md
- ngx_http_vod_request_parse.c
- vod/media_set_parser.c
Instruct the client to select by default a rendition matching the current playback environment in the absence of explicit user preference.
> Ensure that sequence autoselect is enabled by default

- README.md
- vod/dash/dash_packager.c
- vod/manifest_utils.c
- vod/media_set_parser.c
Address limitations introduced via #5 and #6. Now `roles`, `characteristics`, and `forced` have their own track group. 
- Some player implementations rely on different `label`, therefore it's advised to manually set the `label` when using `roles`, `characteristics`, or `forced` for **non-video** tracks.
> Ensure that track grouping is correct

- vod/dash/dash_packager.c
- vod/hls/m3u8_builder.c
- vod/manifest_utils.c
Summary of the changes:
- Add `group` attribute to all `AdaptationSet`
- Add missing `id`, `lang`, and `contentType` attributes to `AdaptationSet`
- Remove non-standard `label` attribute from `AdaptationSet`
- Add spec-compliant `Label` to `AdaptationSet`
- Fix manifest memory size allocation
> **Note**: The module now has basic support for localized video in DASH.
> Improve compliance with DASH specification

- README.md
- vod/dash/dash_packager.c
Add the same capability already available for HLS to DASH. The sequence ID, when specified, will replace the sequence index in the representation ID.
>  Support sequence ID in the representation ID 

- README.md
- config
The `clock_gettime()` function is provided by `time.h` and expects two arguments.
> Ensure that clock_gettime check works

- vod/dash/dash_packager.c
Address the issue introduced via #17. When a single sequence is defined, the DASH representation ID is straightforward and does not include the sequence index or sequence ID.
Fixes #21
> Fix DASH representation ID for single sequence

- vod/dash/dash_packager.c
Address regression introduced via #17. Users reported playback startup failures, stalling, and infinite buffering on Sony PS4 and Sky Q.
> Ensure that DASH request version is correct

- Dockerfile
- sample/expires.conf
- sample/nginx.conf
Add `Cache-Control` for non-2xx responses to mitigate transient upstream errors (backpressure handling).
> Improve sample cache control

- README.md
Below is a comprehensive list of Kernel parameters commonly tuned to optimize networking performance, especially for high-throughput:
| parameter                          | value               |
| ---------------------------------- | ------------------- |
| net.core.netdev_max_backlog        | 65536               |
| net.core.rmem_default              | 262144              |
| net.core.wmem_default              | 262144              |
| net.core.rmem_max                  | 8388608             |
| net.core.wmem_max                  | 8388608             |
| net.ipv4.tcp_max_orphans           | 262144              |
| net.ipv4.tcp_rmem                  | 4096 262144 8388608 |
| net.ipv4.tcp_wmem                  | 4096 262144 8388608 |
| vm.swappiness                      | 0 …
> Add Kernel parameter tuning recommendations

- .github/workflows/main.yml
- Dockerfile
Update NGINX to latest stable [v1.28.0](https://nginx.org/en/CHANGES-1.28). No impacting changes introduced.
> Update nginx to v1.28.0

- vod/hls/m3u8_builder.c
Replace `#define` with `static const`. Improve readability by using `vod_sprintf` over `vod_copy` when appropriate. Avoid allocation of unnecessary memory.
> Improve HLS builder memory usage and constants

- README.md
- ngx_http_vod_hls.c
- ngx_http_vod_hls_commands.h
- vod/hls/m3u8_builder.c
- vod/hls/m3u8_builder.h
Recent changes via #32 and #26 made the module too opinionated regarding which HLS version should be used, which restricted certain use cases.
The HLS version can now be explicitly set using the vod_hls_version directive. A warning will be logged if a potentially incorrect version is detected.
This change provides more flexibility for different requirements and avoids hardcoded assumptions about the HLS version.
> Allow HLS version tuning

- vod/hls/m3u8_builder.c
Enhances the existing `VIDEO-RANGE` attribute support, aligning it with the HLS version 10 specification.
In HLS version 8, `VIDEO-RANGE` was introduced with two valid values: `SDR` and `PQ`. `SDR` applied when all video used TransferCharacteristics code point `1`, while `PQ` applied if any content used code point `16` or `18`. In all other cases, the attribute must be omitted.
In HLS version 10, the the valid values were expanded to include `HLG`, and the definition of `SDR` was broadened to include additional code points (`1`, `6`, `13`, `14`, `15`). `HLG` is required when video is encoded using code point `18` or mixed with `SDR` content. `PQ` applies when video uses code point `16` or is mixed with `SDR` or `HLG` content.
Its absence implies a default value of `SDR`.
> Add video range HLG support

- vod/hls/m3u8_builder.c
As a follow-up to #38, extends the definition of `SDR` to include additional TransferCharacteristics code points (`1`, `6`, `13`, `14`, `15`) as introduced in HLS version 10.
> Extend video range SDR support

- vod/dash/edash_packager.c
As a follow-up to #37, replaces `#define` with `static const` and make `mpd_*_system_id` read-only.
> Improve encrypted DASH packager constants 

- README.md
- config
- demo/drm/tears-of-steel
- ngx_http_vod_dash.c
- ngx_http_vod_hls.c
- sample/nginx.conf
- vod/dash/dash_packager.c
- vod/dash/edash_packager.c
- vod/dash/edash_packager.h
- vod/hls/hls_encryption.h
- vod/hls/m3u8_builder.c
- vod/manifest_utils.c
- vod/mp4/mp4_pssh.c
- vod/mp4/mp4_pssh.h
Fixes the content protection signaling for `SAMPLE-AES-CTR`, ensuring PlayReady, Widevine, and PSSH v0-compatible systems are correctly represented in the manifest.
Additionally, write the PSSH boxes to MP4 media initialization and updates the MP4 major brand from `isom` to `iso5`.
The `sample-aes-cenc` encryption method is now deprecated in favor of `sample-aes-ctr`.
> AV1 is not yet compatible with this encryption method.
More at [using content protection systems with HLS](https://developer.apple.com/documentation/http-live-streaming/using-content-protection-systems-with-hls).
> Add multi-DRM support for HLS SAMPLE-AES-CTR

- README.md
https://github.com/diogoazevedos/nginx-vod-module/blob/f8c165908f30475953187c245e889b45101157db/ngx_http_vod_dash.c#L562
The default value of `vod_dash_fragment_file_name_prefix` is `fragment`, not `frag`.
> Fix `vod_dash_fragment_file_name_prefix` default value

- vod/subtitle/dfxp_format.c
Remove usage of the deprecated `recovery` attribute from `libxml2`, which was introduced in `v2.14.0` via https://github.com/GNOME/libxml2/commit/712a31abe458eed75f0e2a442b35af58cf7091ca.
> Remove `libxml2` deprecation error

- ngx_http_vod_hls.c
- vod/hls/m3u8_builder.c
- vod/hls/m3u8_builder.h
Adds support for the `#EXT-X-SESSION-KEY` tag in HLS playlists, allowing the player to initiate certificate exchanges earlier and reduce playback startup time. **Note** that only a single session key is supported in this implementation.
> Add HLS session key support

- .github/workflows/main.yml
- Dockerfile
NGINX maintains two release branches: **stable** and **mainline**. Modules should support these actively maintained versions.
> Build against stable and mainline nginx

- Dockerfile
Improves Docker build flexibility by allowing a custom NGINX version via `--build-arg NGINX_VERSION=1.28.0`.
> Parameterize nginx version via docker build

- ngx_http_vod_dash.c
- ngx_http_vod_dash_commands.h
- vod/dash/dash_packager.h
- vod/dash/edash_packager.c
As mentioned on #43, removes the non-documented config `vod_dash_write_playready_kid` and make its behavior permanent.
> Drop legacy DASH PlayReady signaling

- README.md
- ngx_http_vod_hls.c
The minimum HLS version for the CMAF compliance goal is `6`. Most devices from *2016 onwards* support higher versions.
> Bump default HLS version to 6

- README.md
- ngx_http_vod_dash.c
- ngx_http_vod_dash_commands.h
- vod/dash/dash_packager.c
- vod/dash/dash_packager.h
The `BaseURL` is largely compatible with devices released from *2016 onwards*.
> Remove unnecessary DASH base url config

- .github/workflows/main.yml
- Dockerfile
Update NGINX to latest mainline v1.29.1. No impacting changes introduced.
> Update nginx to v1.29.1

- vod/dash/dash_packager.c
Fixes the `@value` of `AudioChannelConfiguration` for the URI `urn:mpeg:dash:23003:3:audio_channel_configuration:2011` by using the correct `ChannelConfiguration` value defined in [ISO/IEC 23091-3:2018](https://www.iso.org/standard/73413.html) instead of hard-coding `1` (as required by [ISO/IEC 23009-1:2022](https://www.iso.org/standard/83314.html) § 5.8.5.4).
> Ensure that DASH audio channels are correct
